name: CI - Sync AppleDB IPSW

on:
  schedule:
  - cron: "0 */4 * * *"
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}

jobs:
  build:
    name: CI - Sync AppleDB IPSW
    runs-on: ubuntu-latest

    env:
      IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
      IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Free up space
        run: |
          /bin/rm -rf /Applications/Xcode_16.1_beta.app
          /bin/rm -rf /Applications/Xcode_16_beta_6.app
          /bin/rm -rf /Applications/Xcode_15.3.app
          /bin/rm -rf /Applications/Xcode_15.2.app
          /bin/rm -rf /Applications/Xcode_15.1.app
          /bin/rm -rf /Applications/Xcode_15.0.1.app
          /bin/rm -rf /Applications/Xcode_14.3.1.app
          /bin/rm -rf /Users/runner/Library/Android/sdk

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Sync Installers
        run: python3 main.py --access_key $IA_ACCESS_KEY --secret_key $IA_SECRET_KEY --variant "AppleDB IPSW"